package src.AI;

import src.game.AbstractPlayer;
import src.game.DotsAndBoxesGame;
import src.game.DotsAndBoxesMove;
import java.util.Random;

import java.util.ArrayList;
import java.util.List;

public class DumbAI extends AbstractPlayer {

    /**
     * Creates a new src.game.AbstractPlayer object.
     *
     * @param name
     */
    //@ requires name != null;
    //@ ensures getName().equals(name);
    public DumbAI(String name) {
        super(name);
    }

    /**
     * Generates a move by randomly picking a valid index
     * @param game the current src.game
     * @return the Move randomly generated by the computer
     */
    //@ requires game != null;
    //@ ensures \result != null;
    //@ pure
    public DotsAndBoxesMove determineMove(DotsAndBoxesGame game) {
        List<DotsAndBoxesMove> validMoves = game.getValidMoves();
//        System.out.println(validMoves);
//        System.out.println((validMoves.size()));
        return validMoves.get((new Random()).nextInt(validMoves.size()));
    }
}
